[metadata]
name = ckanext-oauth2-login
version = 0.1.0
description = ORCID OAuth2 login for CKAN
long_description = file: README.md
long_description_content_type = text/markdown
license = AGPL-3.0

[options]
packages = find_namespace:
include_package_data = True
install_requires =
    requests

[options.packages.find]
include = ckanext*

[options.entry_points]
ckan.plugins =
    oauth2_login = ckanext.oauth2_login.plugin:OAuth2LoginPlugin
