[project]
name = "ckanext-obis_schema"
version = "0.0.1"
description = "OBIS Products Catalog schema, facets, and Solr indexing."
readme = "README.md"
authors = [
    {name = "OBIS", email = "helpdesk@obis.org"}
]
license = {text = "AGPL"}
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Programming Language :: Python :: 3.10",
]

keywords = ["CKAN"]
dependencies = []

[project.entry-points."ckan.plugins"]
obis_schema = "ckanext.obis_schema.plugin:ObisSchemaPlugin"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings = [
        "ignore::sqlalchemy.exc.SADeprecationWarning",
        "ignore::sqlalchemy.exc.SAWarning",
        "ignore::DeprecationWarning",
]
addopts = "--ckan-ini test.ini"