title: OBIS Products Catalog
description: A comprehensive metadata catalog for ocean biodiversity data products

# Remote theme only (no "theme:" line)
remote_theme: just-the-docs/just-the-docs

# Plugins
plugins:
  - jekyll-remote-theme

# Color scheme - change to a valid one
color_scheme: default

# Logo (optional - add your logo file to docs/assets/images/)
# logo: "/assets/images/obis-logo.png"

# Aux links (top right)
aux_links:
  "OBIS Website":
    - "https://obis.org"
  "GitHub":
    - "https://github.com/iobis/obis-products-catalog"

# Footer
footer_content: "Maintained by the OBIS Products Coordination Group. Licensed under AGPL v3.0."

# Search enabled
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Enable copy code button
enable_copy_code_button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Google Analytics (optional)
# ga_tracking: UA-XXXXXXXXX-X

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock