title: OBIS Products Catalog
description: A comprehensive metadata catalog for ocean biodiversity data products
theme: jekyll-theme-cayman
show_downloads: false

# Navigation
nav_links:
  - title: Home
    url: /
  - title: User Guide
    url: /user-guide
  - title: API Docs
    url: /api-docs
  - title: Developer Guide
    url: /developer-guide
  - title: GitHub
    url: https://github.com/iobis/obis-products-catalog

# Footer
footer_text: |
  Maintained by the OBIS Products Coordination Group
  
# Google Analytics (optional - add your tracking ID)
# google_analytics: UA-XXXXXXXXX-X

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock